# Cross-reference for Microsoft SKUs to human-readable license names

$MicrosoftSkuCrossReference = @{
	"AAD_BASIC"                          = "Azure Active Directory Basic"
	"AAD_PREMIUM"                        = "Azure Active Directory Premium P1" #Changed
	"AAD_PREMIUM_P2"                     = "Azure Active Directory Premium P2" #New
	"ATA"                                = "Advanced Threat Analytics"
	"ADALLOM_O365"                       = "Office 365 Cloud App Security"
	"ATP_ENTERPRISE"                     = "Exchange Online Advanced Threat Protection"
	"BI_AZURE_P1"                        = "Power BI Reporting and Analytics"
	"BPOS_S_TODO_1"                      = "Microsoft To Do"
	"CRMIUR"                             = "CMRIUR"
	"CRMSTANDARD"                        = "Microsoft Dynamics CRM Online Professional"
	"CRMSTORAGE"                         = "Microsoft Dynamics CRM Online Additional Storage"
	"DESKLESSPACK"                       = "Office 365 (Plan K1)"
	"DESKLESSPACK_GOV"                   = "Microsoft Office 365 (Plan K1) for Government"
	"DESKLESSWOFFPACK"                   = "Office 365 (Plan K2)"
	"DYN365_ENTERPRISE_P1_IW"            = "Dynamics 365 P1 Trial for Information Workers"
	"DYN365_ENTERPRISE_PLAN1"            = "Dynamics 365 Customer Engagement Plan Enterprise Edition"
	"DYN365_ENTERPRISE_SALES"            = "Dynamics Office 365 Enterprise Sales"
	"DYN365_ENTERPRISE_TEAM_MEMBERS"     = "Dynamics 365 For Team Members Enterprise Edition"
	"DYN365_FINANCIALS_BUSINESS_SKU"     = "Dynamics 365 for Financials Business Edition"
	"DYN365_FINANCIALS_TEAM_MEMBERS_SKU" = "Dynamics 365 for Team Members Business Edition"
	"DYN365_TEAM_MEMBERS"                = "Dynamics 365 Team Members"
	"ECAL_SERVICES"                      = "ECAL"
	"EMS"                                = "Enterprise Mobility Suite"
	"EMSPREMIUM"                         = "ENTERPRISE MOBILITY + SECURITY E5"
	"ENTERPRISEPACK"                     = "Office 365 Enterprise E3" #Modified
	"ENTERPRISEPACK_B_PILOT"             = "Office 365 (Enterprise Preview)"
	"ENTERPRISEPACK_FACULTY"             = "Office 365 (Plan A3) for Faculty"
	"ENTERPRISEPACK_GOV"                 = "Microsoft Office 365 (Plan G3) for Government"
	"ENTERPRISEPACK_STUDENT"             = "Office 365 (Plan A3) for Students"
	"ENTERPRISEPACKLRG"                  = "Office 365 Enterprise E3" #Modified
	"ENTERPRISEPREMIUM"                  = "Enterprise E5 (with Audio Conferencing)"
	"ENTERPRISEPREMIUM_NOPSTNCONF"       = "Enterprise E5 (without Audio Conferencing)"
	"ENTERPRISEWITHSCAL"                 = "Office 365 Enterprise E4" #Modified
	"ENTERPRISEWITHSCAL_FACULTY"         = "Office 365 (Plan A4) for Faculty"
	"ENTERPRISEWITHSCAL_GOV"             = "Microsoft Office 365 (Plan G4) for Government"
	"ENTERPRISEWITHSCAL_STUDENT"         = "Office 365 (Plan A4) for Students"
	"EOP_ENTERPRISE_FACULTY"             = "Exchange Online Protection for Faculty"
	"EQUIVIO_ANALYTICS"                  = "Office 365 Advanced eDiscovery"
	"ESKLESSWOFFPACK_GOV"                = "Microsoft Office 365 (Plan K2) for Government"
	"EXCHANGE_ANALYTICS"                 = "Microsoft MyAnalytics" #New
	"EXCHANGE_L_STANDARD"                = "Exchange Online (Plan 1)"
	"EXCHANGE_S_ARCHIVE_ADDON_GOV"       = "Exchange Online Archiving"
	"EXCHANGE_S_DESKLESS"                = "Exchange Online Kiosk"
	"EXCHANGE_S_DESKLESS_GOV"            = "Exchange Kiosk"
	"EXCHANGE_S_ENTERPRISE_GOV"          = "Exchange Plan 2G"
	"EXCHANGE_S_STANDARD_MIDMARKET"      = "Exchange Online (Plan 1)"
	"EXCHANGEARCHIVE_ADDON"              = "Exchange Online Archiving For Exchange Online"
	"EXCHANGEDESKLESS"                   = "Exchange Online Kiosk"
	"EXCHANGEENTERPRISE"                 = "Exchange Online Plan 2"
	"EXCHANGEENTERPRISE_GOV"             = "Microsoft Office 365 Exchange Online (Plan 2) only for Government"
	"EXCHANGESTANDARD"                   = "Office 365 Exchange Online Plan 1"
	"EXCHANGESTANDARD_GOV"               = "Microsoft Office 365 Exchange Online (Plan 1) only for Government"
	"EXCHANGESTANDARD_STUDENT"           = "Exchange Online (Plan 1) for Students"
	"FLOW_FREE"                          = "Microsoft Flow Free"
	"FLOW_P1"                            = "Microsoft Flow Plan 1"
	"FLOW_P2"                            = "Microsoft Flow Plan 2"
	"INTUNE_A"                           = "Windows Intune Plan A"
	"LITEPACK"                           = "Office 365 (Plan P1)"
	"MCOCAP"                             = "Common Area Phone" #New
	"MCOEV"                              = "Microsoft 365 Phone System" #Changed
	"MCOLITE"                            = "Lync Online (Plan 1)"
	"MCOMEETACPEA"                       = "Audio Conferencing Pay-Per-Minute" #New
	"MCOMEETADV"                         = "PSTN conferencing"
	"MCOPSTN1"                           = "Domestic Calling Plan" #new
	"MCOPSTN2"                           = "Domestic and International Calling Plan"
	"MCOPSTNC"                           = "Communication Credits" #New
	"MCOSTANDARD"                        = "Skype for Business Online Standalone Plan 2"
	"MCOSTANDARD_GOV"                    = "Lync Plan 2G"
	"MCOSTANDARD_MIDMARKET"              = "Lync Online (Plan 1)"
	"MFA_PREMIUM"                        = "Azure Multi-Factor Authentication"
	"MICROSOFT_BUSINESS_CENTER"          = "Microsoft Business Center"
	"O365_BUSINESS"                      = "Office 365 Business"
	"O365_BUSINESS_ESSENTIALS"           = "Microsoft 365 Business Basic" #Changed
	"O365_BUSINESS_PREMIUM"              = "Microsoft 365 Business Standard" #Changed
	"OFFICE_PRO_PLUS_SUBSCRIPTION_SMBIZ" = "Apps for Enterprise (formerly Office ProPlus)" #Changed
	"OFFICESUBSCRIPTION"                 = "Apps for Enterprise (formerly Office ProPlus)" #Changed
	"OFFICESUBSCRIPTION_GOV"             = "Apps for Enterprise (formerly Office ProPlus)" #Changed
	"OFFICESUBSCRIPTION_STUDENT"         = "Apps for Enterprise (formerly Office ProPlus) Student Benefit" #Changed
	"NONPROFIT_PORTAL"                   = "Nonprofit Portal" #New
	"PHONESYSTEM_VIRTUALUSER"            = "Microsoft 365 Phone System - Virtual User" #New
	"PLANNERSTANDALONE"                  = "Planner Standalone"
	"POWER_BI_ADDON"                     = "Office 365 Power BI Addon"
	"POWER_BI_INDIVIDUAL_USE"            = "Power BI Individual User"
	"POWER_BI_PRO"                       = "Power BI Pro"
	"POWER_BI_STANDALONE"                = "Power BI Stand Alone"
	"POWER_BI_STANDARD"                  = "Power-BI Standard"
	"POWERAPPS_VIRAL"                    = "Microsoft PowerApps Plan 2 Trial" #New
	"PROJECT_MADEIRA_PREVIEW_IW_SKU"     = "Dynamics 365 for Financials for IWs"
	"PROJECTCLIENT"                      = "Project Professional"
	"PROJECTESSENTIALS"                  = "Project Lite"
	"PROJECTONLINE_PLAN_1"               = "Project Online Plan 1" #Changed
	"PROJECTONLINE_PLAN_2"               = "Project Online Plan 2" #Changed
	"ProjectPremium"                     = "Project Online Premium"
	"PROJECTPROFESSIONAL"                = "Project Professional"
	"PROJECTWORKMANAGEMENT"              = "Office 365 Planner Preview"
	"RIGHTSMANAGEMENT"                   = "Azure Information Protcetion Plan 1" #Changed
	"RIGHTSMANAGEMENT_ADHOC"             = "Windows Azure Rights Management"
	"RMS_S_ENTERPRISE"                   = "Azure Active Directory Rights Management"
	"RMS_S_ENTERPRISE_GOV"               = "Windows Azure Active Directory Rights Management"
	"SHAREPOINTDESKLESS"                 = "SharePoint Online Kiosk"
	"SHAREPOINTDESKLESS_GOV"             = "SharePoint Online Kiosk"
	"SHAREPOINTENTERPRISE_GOV"           = "SharePoint Plan 2G"
	"SHAREPOINTENTERPRISE_MIDMARKET"     = "SharePoint Online (Plan 1)"
	"SHAREPOINTLITE"                     = "SharePoint Online (Plan 1)"
	"SHAREPOINTSTANDARD"                 = "SharePoint Online (Plan 1)" #New
	"SHAREPOINTSTORAGE"                  = "SharePoint storage"
	"SHAREPOINTWAC"                      = "Office Online"
	"SHAREPOINTWAC_GOV"                  = "Office Online for Government"
	"SMB_BUSINESS_PREMIUM"               = "Microsoft 365 Business Standard (SMB)" #New
	"SMB_APPS"                           = "Microsoft Business Apps"
	"SPB"                                = "Microsoft 365 Business Premium" #New
	"SPE_E3"                             = "Microsoft 365 E3"
	"SPE_E5"                             = "Microsoft 365 E5"
	"SPZA_IW"                            = "App Connect"
	"STANDARD_B_PILOT"                   = "Office 365 (Small Business Preview)"
	"STANDARDPACK"                       = "Office 365 Enterprise E1" #Changed
	"STANDARDPACK_FACULTY"               = "Office 365 (Plan A1) for Faculty"
	"STANDARDPACK_GOV"                   = "Microsoft Office 365 (Plan G1) for Government"
	"STANDARDPACK_STUDENT"               = "Office 365 (Plan A1) for Students"
	"STANDARDWOFFPACK"                   = "Office 365 Enterprise E2" #Changed
	"STANDARDWOFFPACK_FACULTY"           = "Office 365 Education E1 for Faculty"
	"STANDARDWOFFPACK_GOV"               = "Microsoft Office 365 (Plan G2) for Government"
	"STANDARDWOFFPACK_IW_FACULTY"        = "Office 365 Education for Faculty"
	"STANDARDWOFFPACK_IW_STUDENT"        = "Office 365 Education for Students"
	"STANDARDWOFFPACK_STUDENT"           = "Microsoft Office 365 (Plan A2) for Students"
	"STANDARDWOFFPACKPACK_FACULTY"       = "Office 365 (Plan A2) for Faculty"
	"STANDARDWOFFPACKPACK_STUDENT"       = "Office 365 (Plan A2) for Students"
	"STREAM"                             = "Microsoft Stream Trial"
	"TEAMS_EXPLORATORY"                  = "Microsoft Teams Exploratory" #New
	"TEAMS1"                             = "Microsoft Teams" #New
	"VIDEO_INTEROP"                      = "Polycom Skype Meeting Video Interop for Skype for Business"
	"VISIOCLIENT"                        = "Visio Online Plan 2 (Was Visio Pro)" #Changed
	"VISIOONLINE_PLAN1"                  = "Visio Online Plan 1"
	"WINBIZ"                             = "Windows 10 Business" #New
	"WINDOWS_STORE"                      = "Windows Store for Business"
	"YAMMER_ENTERPRISE"                  = "Yammer for the Starship Enterprise"
	"YAMMER_MIDSIZE"                     = "Yammer"
}